export type ScaleOption = { label: string; help: string };

export const SCALES: Record<string, ScaleOption[]> = {
  coverage_more: [
    { label: "None of it", help: "Nothing is written down." },
    { label: "Only a little", help: "A small part is written down." },
    { label: "About half", help: "About half is written down." },
    { label: "Most of it", help: "Most of it is written down." },
    { label: "Nearly all", help: "Nearly all of it is written down." },
    { label: "All of it, kept current", help: "Written down and kept up to date." },
  ],
  consistency_more: [
    { label: "Different everywhere", help: "Every team does it their own way." },
    { label: "Mostly different", help: "Most teams differ from each other." },
    { label: "Mixed", help: "Some teams match, some do not." },
    { label: "Mostly the same", help: "Nearly every team works the same way." },
    { label: "Almost the same", help: "The same everywhere, with rare exceptions." },
    { label: "Exactly the same", help: "Exactly the same way, every time." },
  ],
  ownership_more: [
    { label: "Nobody", help: "Nobody knows who is responsible." },
    { label: "It is vague", help: "It is not clear who is responsible." },
    { label: "Some jobs", help: "Some jobs have an owner." },
    { label: "Most jobs", help: "Most jobs have an owner." },
    { label: "Every main job", help: "Every main job has a named owner." },
    { label: "Owner who checks", help: "An owner reviews each job regularly." },
  ],
  stepcount: [
    { label: "More than 10 steps", help: "More than ten separate steps." },
    { label: "6 to 10 steps", help: "Six to ten steps." },
    { label: "4 or 5 steps", help: "Four or five steps." },
    { label: "About 3 steps", help: "About three steps." },
    { label: "About 2 steps", help: "About two steps." },
    { label: "One step", help: "One step, start to finish." },
  ],
  approvals: [
    { label: "Five or more people", help: "Five or more people must approve it." },
    { label: "Three or four people", help: "Three or four people must approve it." },
    { label: "Two people", help: "Two people must approve it." },
    { label: "One manager", help: "Only one manager approves it." },
    { label: "Often not at all", help: "Often no approval is needed." },
    { label: "Never needs approval", help: "It never needs approval — it just runs." },
  ],
  waiting_less: [
    { label: "Almost all waiting", help: "Nearly all the time is spent waiting." },
    { label: "Most of it waiting", help: "Most of the time is spent waiting." },
    { label: "Half waiting", help: "Waiting and working are about equal." },
    { label: "A small wait", help: "Waiting is a small part of the time." },
    { label: "Rarely any wait", help: "Waiting is rare." },
    { label: "No waiting", help: "Virtually no waiting." },
  ],
  idletime_less: [
    { label: "All the time", help: "People sit idle almost all the time." },
    { label: "Most days", help: "Idle on most working days." },
    { label: "Most weeks", help: "Idle most weeks." },
    { label: "Occasionally", help: "Idle from time to time." },
    { label: "Rarely", help: "Rarely idle." },
    { label: "Practically never", help: "Practically no idle time." },
  ],
  overtime_less: [
    { label: "Every week", help: "Extra hours every week." },
    { label: "Most weeks", help: "Extra hours most weeks." },
    { label: "Most months", help: "Extra hours most months." },
    { label: "A few times a year", help: "A few times a year." },
    { label: "Very rarely", help: "Very rarely needed." },
    { label: "Never", help: "Normal hours are always enough." },
  ],
  balance_more: [
    { label: "Always overloaded", help: "One team always overloaded, another idle." },
    { label: "Most months", help: "Imbalance most months." },
    { label: "A few times a year", help: "A few times a year." },
    { label: "Occasionally", help: "Happens occasionally." },
    { label: "Mostly fair", help: "Work is mostly shared fairly." },
    { label: "Always fair", help: "Work is always shared fairly." },
  ],
  repetition: [
    { label: "Never repeats", help: "Every job is different." },
    { label: "Rarely repeats", help: "Work very rarely repeats." },
    { label: "A few times a month", help: "Repeats a few times a month." },
    { label: "Most days", help: "Repeats on most days." },
    { label: "Many times a day", help: "Repeats many times a day." },
    { label: "All day, every day", help: "The same work all day, every day." },
  ],
  schedule_more: [
    { label: "Comes whenever", help: "It comes whenever it comes." },
    { label: "Rarely the same", help: "Rarely the same time." },
    { label: "Sometimes regular", help: "Regular from time to time." },
    { label: "Mostly scheduled", help: "Mostly on a schedule." },
    { label: "Nearly always", help: "Nearly always on a schedule." },
    { label: "Fixed schedule", help: "Exactly on a set schedule." },
  ],
  cover_less: [
    { label: "Work stops", help: "The work stops if that person is away." },
    { label: "Stops mostly", help: "Most of the work stops." },
    { label: "Someone finishes part", help: "Someone else can finish part of it." },
    { label: "Someone finishes most", help: "Someone else can finish most of it." },
    { label: "Someone finishes all", help: "Someone else can finish all of it." },
    { label: "Anyone can do it", help: "Anyone trained can do it." },
  ],
  rules_more: [
    { label: "Decided by feel", help: "People decide by feel." },
    { label: "Very few written", help: "Very few rules are written down." },
    { label: "Some written", help: "Some rules are written down." },
    { label: "Most written", help: "Most decisions follow written rules." },
    { label: "Nearly all written", help: "Nearly all decisions follow written rules." },
    { label: "Every rule written", help: "Every decision follows a written rule." },
  ],
  conditions_more: [
    { label: "Chosen by feel", help: "Conditions are not written." },
    { label: "Hardly ever", help: "Hardly ever written." },
    { label: "Sometimes", help: "Sometimes written." },
    { label: "Mostly", help: "Mostly written down." },
    { label: "Nearly always", help: "Nearly always written." },
    { label: "Always and clear", help: "Always written and clear." },
  ],
  exception_less: [
    { label: "Almost every time", help: "Something unexpected almost every time." },
    { label: "Most of the time", help: "Unexpected most of the time." },
    { label: "Often", help: "Happens often." },
    { label: "Sometimes", help: "From time to time." },
    { label: "Rarely", help: "Happens rarely." },
    { label: "Almost never", help: "Almost never happens." },
  ],
  effort_less: [
    { label: "Nearly all day", help: "Takes up nearly the whole day." },
    { label: "Most of the day", help: "Most of the working day." },
    { label: "About half the day", help: "About half the day." },
    { label: "A small part", help: "A small part of the day." },
    { label: "Very little", help: "Very little time." },
    { label: "Almost none", help: "It happens on its own." },
  ],
  copying_less: [
    { label: "All day, every day", help: "Copied all day, every day." },
    { label: "Most days", help: "Copied on most days." },
    { label: "Most weeks", help: "Copied most weeks." },
    { label: "Sometimes", help: "From time to time." },
    { label: "Rarely", help: "Rarely copied." },
    { label: "Never", help: "Information moves on its own." },
  ],
  software_count: [
    { label: "None at all", help: "Everything is Word and spreadsheets." },
    { label: "One area", help: "One part has its own software." },
    { label: "Two areas", help: "Two parts have their own software." },
    { label: "About half", help: "About half the business has software." },
    { label: "Most areas", help: "Most parts have software built for them." },
    { label: "Every area", help: "Every area that needs it has dedicated software." },
  ],
  share_more: [
    { label: "None", help: "None of it." },
    { label: "A small part", help: "A small part of it." },
    { label: "About a quarter", help: "About a quarter of it." },
    { label: "About half", help: "About half of it." },
    { label: "Most of it", help: "Most of it." },
    { label: "All of it", help: "All of it." },
  ],
  outage_less: [
    { label: "Business stops", help: "The business stops completely." },
    { label: "Most work stops", help: "Most of the work stops." },
    { label: "Big parts stop", help: "Big parts of the business stop." },
    { label: "A few areas held up", help: "A few areas are held up." },
    { label: "Small delays only", help: "Only small delays." },
    { label: "Nothing important stops", help: "Nothing important stops." },
  ],
  paper_less: [
    { label: "Almost all of it", help: "Almost all daily work is on paper." },
    { label: "Most of it", help: "Most work still starts or ends on paper." },
    { label: "About half", help: "About half is still paper." },
    { label: "A small part", help: "A small part is paper." },
    { label: "Rarely", help: "Paper is rare." },
    { label: "Never", help: "Work is fully digital." },
  ],
  email_less: [
    { label: "Almost everything", help: "Almost all arranging happens in email." },
    { label: "Most of it", help: "Most arranging happens in email." },
    { label: "About half", help: "About half is email." },
    { label: "A small part", help: "A small part is email." },
    { label: "Rarely", help: "Email is rarely the system of work." },
    { label: "Never", help: "Work runs in systems, not inboxes." },
  ],
  spreadsheet_less: [
    { label: "The official record", help: "Spreadsheets are the system of record." },
    { label: "Most important jobs", help: "Most important jobs live in spreadsheets." },
    { label: "Several jobs", help: "Several important jobs live there." },
    { label: "A few jobs", help: "A few jobs still live there." },
    { label: "Rarely", help: "Rarely the official record." },
    { label: "Never", help: "Governed systems hold the record." },
  ],
  integration_more: [
    { label: "None", help: "No systems pass information automatically." },
    { label: "One or two", help: "One or two connections exist." },
    { label: "A few", help: "A few systems are connected." },
    { label: "About half", help: "About half are connected." },
    { label: "Most", help: "Most systems pass information." },
    { label: "All core systems", help: "All core systems are connected." },
  ],
  dataquality_less: [
    { label: "Constantly", help: "This happens constantly." },
    { label: "Most weeks", help: "Most weeks." },
    { label: "Most months", help: "Most months." },
    { label: "Occasionally", help: "Occasionally." },
    { label: "Rarely", help: "Rarely." },
    { label: "Almost never", help: "Almost never." },
  ],
  captured_more: [
    { label: "Written down later", help: "Recorded later from memory." },
    { label: "Mostly later", help: "Mostly written down later." },
    { label: "Mixed", help: "Some captured live, some later." },
    { label: "Mostly live", help: "Mostly captured while work is done." },
    { label: "Almost always live", help: "Almost always captured live." },
    { label: "Automatically", help: "Recorded automatically as work happens." },
  ],
  kpi_more: [
    { label: "None agreed", help: "No agreed measures." },
    { label: "Informal", help: "Informal numbers, not consistent." },
    { label: "A few, irregular", help: "A few measures, tracked irregularly." },
    { label: "A few, consistent", help: "A few measures, tracked the same way." },
    { label: "A small set, disciplined", help: "A small set, always the same way." },
    { label: "Live operating measures", help: "A live set that drives decisions." },
  ],
  dashboard_more: [
    { label: "Must ask someone", help: "A manager must ask for a report." },
    { label: "Monthly pack only", help: "Only a monthly pack." },
    { label: "Weekly pack", help: "A weekly pack, after the fact." },
    { label: "Some live screens", help: "Some live screens exist." },
    { label: "Most measures live", help: "Most measures are live." },
    { label: "Live without asking", help: "A manager can see live results without asking." },
  ],
  reliability_more: [
    { label: "Whenever they arrive", help: "Reports arrive whenever they arrive." },
    { label: "Often late", help: "Often late." },
    { label: "Usually on time", help: "Usually on time." },
    { label: "On a known day", help: "On a known day, most months." },
    { label: "Reliable each month", help: "Reliable the same day each month." },
    { label: "Always on the same day", help: "Always the same reliable day." },
  ],
  volume_count: [
    { label: "None", help: "Almost none." },
    { label: "Fewer than 10 a week", help: "Fewer than ten a week." },
    { label: "10 to 30 a week", help: "Ten to thirty a week." },
    { label: "30 to 100 a week", help: "Thirty to a hundred a week." },
    { label: "100 to 300 a week", help: "A hundred to three hundred a week." },
    { label: "More than 300 a week", help: "More than three hundred a week." },
  ],
  repeats_count: [
    { label: "Almost none repeat", help: "Almost every question is unique." },
    { label: "A small share", help: "A small share repeats." },
    { label: "About a quarter", help: "About a quarter repeat." },
    { label: "About half", help: "About half repeat." },
    { label: "Most of them", help: "Most of them repeat." },
    { label: "Almost all of them", help: "Almost all of them are the same." },
  ],
  knowledge_more: [
    { label: "Nowhere central", help: "No central place." },
    { label: "Scattered files", help: "Scattered files and inboxes." },
    { label: "A shared folder", help: "A shared folder, poorly kept." },
    { label: "A library, uneven", help: "A library, but uneven." },
    { label: "A maintained library", help: "A maintained central library." },
    { label: "Searchable and owned", help: "One searchable, owned knowledge base." },
  ],
  speed_more: [
    { label: "Must ask someone", help: "They must ask someone." },
    { label: "Hours", help: "It takes hours." },
    { label: "About an hour", help: "About an hour." },
    { label: "About 15 minutes", help: "About fifteen minutes." },
    { label: "A few minutes", help: "A few minutes." },
    { label: "Straight away", help: "Straight away." },
  ],
  planning_more: [
    { label: "Day to day", help: "The business lives day to day." },
    { label: "This week", help: "Plans about a week ahead." },
    { label: "This month", help: "Plans about a month ahead." },
    { label: "This quarter", help: "Plans a quarter ahead." },
    { label: "This year", help: "Plans a year ahead." },
    { label: "Multi-year", help: "Plans more than a year ahead, with numbers." },
  ],
  databased_more: [
    { label: "Almost all opinion", help: "Almost entirely opinion." },
    { label: "Mostly opinion", help: "Mostly opinion." },
    { label: "Half and half", help: "Half data, half opinion." },
    { label: "Mostly data", help: "Mostly data." },
    { label: "Nearly all data", help: "Nearly all data." },
    { label: "Only data", help: "Built only on real data." },
  ],
  core_system_more: [
    { label: "No main system", help: "No main system of record." },
    { label: "Several competing", help: "Several competing systems." },
    { label: "One, poorly used", help: "One system, poorly used." },
    { label: "One for some records", help: "One system for some official records." },
    { label: "One for most records", help: "One system for most official records." },
    { label: "One trusted system", help: "One trusted system holds official records." },
  ],
  fit_more: [
    { label: "Gets in the way", help: "Systems get in the way of the work." },
    { label: "Barely used", help: "Bought but barely used." },
    { label: "Partial fit", help: "Partial fit for the work." },
    { label: "Mostly fit", help: "Mostly support the work." },
    { label: "Fit well", help: "Fit the work well." },
    { label: "Built for the work", help: "Actually built for the work they support." },
  ],
  blockers_less: [
    { label: "A long list", help: "A long list of known blockers." },
    { label: "Several serious ones", help: "Several serious blockers." },
    { label: "A few known ones", help: "A few known blockers." },
    { label: "One or two", help: "One or two known blockers." },
    { label: "Almost none", help: "Almost none." },
    { label: "None that matter", help: "None that would stop a connection." },
  ],
  security_more: [
    { label: "No control", help: "No real access control." },
    { label: "Informal", help: "Informal, never reviewed." },
    { label: "A list, rarely checked", help: "A list, rarely checked." },
    { label: "Checked yearly", help: "Checked about once a year." },
    { label: "Checked often", help: "Checked and cleaned often." },
    { label: "Owned and audited", help: "Owned, reviewed, and audited." },
  ],
  restore_more: [
    { label: "Would not recover", help: "Would not know how to recover." },
    { label: "Weeks, untested", help: "Weeks, and never tested." },
    { label: "Days, untested", help: "Days, and never tested." },
    { label: "Days, tested once", help: "Days, tested once." },
    { label: "Hours, tested", help: "Hours, and tested." },
    { label: "Hours, regularly tested", help: "Hours, and regularly tested." },
  ],
  growth_more: [
    { label: "Hire in lockstep", help: "Every increase needs more people." },
    { label: "Almost lockstep", help: "Almost every increase needs more people." },
    { label: "Mostly lockstep", help: "Most growth needs more people." },
    { label: "Some leverage", help: "Some growth without proportional hiring." },
    { label: "Clear leverage", help: "Clear ability to grow without lockstep hiring." },
    { label: "Scale without hiring", help: "Can produce more without hiring many more people." },
  ],
  headroom_more: [
    { label: "Already full", help: "Already at capacity." },
    { label: "Almost full", help: "Almost no room left." },
    { label: "A little room", help: "A little more work is possible." },
    { label: "Some room", help: "Some more work is possible." },
    { label: "Comfortable room", help: "Comfortable room to take more on." },
    { label: "Substantial room", help: "Substantial unused capacity." },
  ],
  keyperson_less: [
    { label: "Would stop", help: "The business would stop." },
    { label: "Most work would stop", help: "Most work would stop." },
    { label: "Serious disruption", help: "Serious disruption." },
    { label: "Manageable disruption", help: "Manageable disruption." },
    { label: "Small disruption", help: "Small disruption." },
    { label: "Would still run", help: "The business would still run." },
  ],
  concentration_less: [
    { label: "Always the same people", help: "Always the same one or two people." },
    { label: "Almost always", help: "Almost always the same people." },
    { label: "Usually", help: "Usually the same people." },
    { label: "Sometimes shared", help: "Sometimes shared." },
    { label: "Mostly shared", help: "Mostly shared across several people." },
    { label: "Distributed", help: "Important decisions are distributed." },
  ],
  succession_more: [
    { label: "No cover", help: "Nobody has been trained to cover." },
    { label: "Informal cover", help: "Informal, untested cover." },
    { label: "One person, untested", help: "One person, untested." },
    { label: "Some trained", help: "Some people have been trained." },
    { label: "Cover for most jobs", help: "Cover exists for most important jobs." },
    { label: "Trained and practised", help: "Cover is trained and practised." },
  ],
  blocker_less: [
    { label: "It is the main limit", help: "This is the main limit on growth." },
    { label: "A serious limit", help: "A serious limit on growth." },
    { label: "A noticeable limit", help: "A noticeable limit." },
    { label: "A small limit", help: "A small limit." },
    { label: "Barely a limit", help: "Barely a limit." },
    { label: "Not a limit", help: "Not a limit on growth." },
  ],
};

export function scoreFromIndex(index: number, length = 6) {
  if (index < 0) return 0;
  const max = Math.max(length - 1, 1);
  return Math.round((Math.min(index, max) / max) * 100);
}
